# Site settings
title: Arka Roy
#email: your-email@domain.com
description: Provides professional services on web design, development, web application, digital marketing, social marketing.
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.arkaroy.net" # the base hostname & protocol for your site
permalink: /:categories/:title/
author:
    name: "Arka Roy"
    email: "i.arkaroy@gmail.com"
    website: "http://www.arkaroy.net"
    facebook: iarkaroy
    twitter: iarkaroy
    behance:  iarkaroy
    github:  iarkaroy
    googleplus: ArkaRoyGPlus
    linkedin: iarkaroy
img: /assets/image/
lastmod: 2015-04-15T23:12:14+05:30

# Build settings
#markdown: kramdown

sass:
    sass_dir: _sass
    style: :compressed